import './Inter.dart';

class Autogenerated {
  List<Inter> inters;
  String keyy;

  Autogenerated({this.inters});

  Autogenerated.fromJson(Map<String, dynamic> json,String temp) {
    this.keyy = temp;
    print(keyy);
    print("fromJson");
    if (json[keyy] != null) {
      print("json[keyy] !!= null");
      inters = new List<Inter>();
      json[keyy].forEach((v) {
        inters.add(new Inter.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.inters != null) {
      data[keyy] =
          this.inters.map((v) => v.toJson()).toList();
    }
    return data;
  }
}